create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  public_id bigint generated by default as identity unique,
  email text not null default '',
  name text not null default '',
  role text not null default 'FAN',
  initials text not null default '',
  avatar_url text not null default '',
  profile jsonb not null default '{}'::jsonb,
  verification jsonb not null default '{}'::jsonb,
  agreements jsonb not null default '{}'::jsonb,
  plan text not null default 'FREE',
  plan_expiry timestamptz,
  plan_billing_cycle text,
  talents_unlocked bigint[] not null default '{}',
  profile_updated_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists user_profiles_public_id_idx on public.user_profiles (public_id);
create index if not exists user_profiles_role_idx on public.user_profiles (role);

drop trigger if exists set_user_profiles_updated_at on public.user_profiles;

create trigger set_user_profiles_updated_at
before update on public.user_profiles
for each row
execute function public.set_updated_at();

create or replace function public.sync_user_profile_from_auth()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  next_email text;
  next_name text;
  next_role text;
begin
  next_email := lower(coalesce(new.email, ''));
  next_name := coalesce(
    nullif(trim(coalesce(new.raw_user_meta_data ->> 'name', '')), ''),
    nullif(split_part(next_email, '@', 1), ''),
    'CrownPoint Member'
  );
  next_role := coalesce(
    nullif(upper(trim(coalesce(new.raw_app_meta_data ->> 'role', new.raw_user_meta_data ->> 'role', ''))), ''),
    'FAN'
  );

  insert into public.user_profiles (
    id,
    email,
    name,
    role,
    initials,
    created_at,
    updated_at
  )
  values (
    new.id,
    next_email,
    next_name,
    next_role,
    '',
    coalesce(new.created_at, timezone('utc', now())),
    timezone('utc', now())
  )
  on conflict (id) do update
    set email = excluded.email,
        name = excluded.name,
        role = excluded.role,
        updated_at = timezone('utc', now());

  return new;
end;
$$;

drop trigger if exists sync_user_profile_from_auth on auth.users;

create trigger sync_user_profile_from_auth
after insert or update of email, raw_user_meta_data, raw_app_meta_data
on auth.users
for each row
execute function public.sync_user_profile_from_auth();

alter table public.user_profiles enable row level security;

drop policy if exists "Users can read own profile" on public.user_profiles;
create policy "Users can read own profile"
on public.user_profiles
for select
using (auth.uid() = id or public.is_admin());

drop policy if exists "Users can insert own profile" on public.user_profiles;
create policy "Users can insert own profile"
on public.user_profiles
for insert
with check (auth.uid() = id or public.is_admin());

drop policy if exists "Users can update own profile" on public.user_profiles;
create policy "Users can update own profile"
on public.user_profiles
for update
using (auth.uid() = id or public.is_admin())
with check (auth.uid() = id or public.is_admin());

drop policy if exists "Users can delete own profile" on public.user_profiles;
create policy "Users can delete own profile"
on public.user_profiles
for delete
using (auth.uid() = id or public.is_admin());
