alter table public.membership_requests
  add column if not exists proof_upload jsonb not null default '{}'::jsonb;

alter table public.orders
  add column if not exists proof_upload jsonb not null default '{}'::jsonb;

create table if not exists public.event_booking_requests (
  id bigint generated by default as identity primary key,
  auth_user_id uuid references auth.users(id) on delete set null,
  user_public_id bigint references public.user_profiles(public_id) on delete set null,
  talent_id bigint not null references public.talents(id) on delete cascade,
  talent_name text not null default '',
  celebrity_name text not null default '',
  event_date date,
  approximate_budget text not null default '',
  event_type text not null default '',
  event_location text not null default '',
  additional_info text not null default '',
  full_name text not null default '',
  organization_name text not null default '',
  job_title text not null default '',
  phone_number text not null default '',
  email_address text not null default '',
  full_address text not null default '',
  nearest_airport text not null default '',
  status text not null default 'NEW',
  reviewed_at timestamptz,
  submitted_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint event_booking_requests_status_check
    check (status in ('NEW', 'IN_REVIEW', 'IN_TOUCH', 'CLOSED'))
);

create index if not exists event_booking_requests_auth_user_id_idx
  on public.event_booking_requests (auth_user_id);
create index if not exists event_booking_requests_user_public_id_idx
  on public.event_booking_requests (user_public_id);
create index if not exists event_booking_requests_talent_id_idx
  on public.event_booking_requests (talent_id);
create index if not exists event_booking_requests_status_idx
  on public.event_booking_requests (status);
create index if not exists event_booking_requests_submitted_at_idx
  on public.event_booking_requests (submitted_at desc);

drop trigger if exists set_event_booking_requests_updated_at on public.event_booking_requests;

create trigger set_event_booking_requests_updated_at
before update on public.event_booking_requests
for each row
execute function public.set_updated_at();

alter table public.event_booking_requests enable row level security;

drop policy if exists "Users can read own event booking requests" on public.event_booking_requests;
create policy "Users can read own event booking requests"
on public.event_booking_requests
for select
using (auth.uid() = auth_user_id or public.is_admin());

drop policy if exists "Users can insert own event booking requests" on public.event_booking_requests;
create policy "Users can insert own event booking requests"
on public.event_booking_requests
for insert
with check (
  public.is_admin()
  or auth.uid() = auth_user_id
  or auth_user_id is null
);

drop policy if exists "Admins can update event booking requests" on public.event_booking_requests;
create policy "Admins can update event booking requests"
on public.event_booking_requests
for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete event booking requests" on public.event_booking_requests;
create policy "Admins can delete event booking requests"
on public.event_booking_requests
for delete
using (public.is_admin());

create table if not exists public.message_threads (
  id bigint generated by default as identity primary key,
  fan_auth_user_id uuid not null references auth.users(id) on delete cascade,
  fan_user_public_id bigint references public.user_profiles(public_id) on delete cascade,
  fan_name text not null default '',
  fan_email text not null default '',
  talent_id bigint not null references public.talents(id) on delete cascade,
  talent_name text not null default '',
  topic text not null default 'Private inbox',
  preview text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  last_active_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint message_threads_fan_talent_unique unique (fan_auth_user_id, talent_id)
);

create index if not exists message_threads_fan_auth_user_id_idx
  on public.message_threads (fan_auth_user_id);
create index if not exists message_threads_talent_id_idx
  on public.message_threads (talent_id);
create index if not exists message_threads_last_active_at_idx
  on public.message_threads (last_active_at desc);

drop trigger if exists set_message_threads_updated_at on public.message_threads;

create trigger set_message_threads_updated_at
before update on public.message_threads
for each row
execute function public.set_updated_at();

alter table public.message_threads enable row level security;

drop policy if exists "Users can read own message threads" on public.message_threads;
create policy "Users can read own message threads"
on public.message_threads
for select
using (public.is_admin() or auth.uid() = fan_auth_user_id);

drop policy if exists "Users can insert own message threads" on public.message_threads;
create policy "Users can insert own message threads"
on public.message_threads
for insert
with check (public.is_admin() or auth.uid() = fan_auth_user_id);

drop policy if exists "Admins can update message threads" on public.message_threads;
create policy "Admins can update message threads"
on public.message_threads
for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Users can delete own message threads" on public.message_threads;
create policy "Users can delete own message threads"
on public.message_threads
for delete
using (public.is_admin() or auth.uid() = fan_auth_user_id);

create table if not exists public.thread_messages (
  id bigint generated by default as identity primary key,
  thread_id bigint not null references public.message_threads(id) on delete cascade,
  sender_role text not null default 'system',
  sender_label text not null default 'System',
  message_text text not null default '',
  attachments jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint thread_messages_sender_role_check
    check (sender_role in ('fan', 'talent', 'system'))
);

create index if not exists thread_messages_thread_id_idx
  on public.thread_messages (thread_id);
create index if not exists thread_messages_created_at_idx
  on public.thread_messages (created_at asc);

drop trigger if exists set_thread_messages_updated_at on public.thread_messages;

create trigger set_thread_messages_updated_at
before update on public.thread_messages
for each row
execute function public.set_updated_at();

alter table public.thread_messages enable row level security;

drop policy if exists "Users can read thread messages" on public.thread_messages;
create policy "Users can read thread messages"
on public.thread_messages
for select
using (
  public.is_admin()
  or exists (
    select 1
    from public.message_threads
    where public.message_threads.id = thread_id
      and public.message_threads.fan_auth_user_id = auth.uid()
  )
);

drop policy if exists "Users can insert thread messages" on public.thread_messages;
create policy "Users can insert thread messages"
on public.thread_messages
for insert
with check (
  public.is_admin()
  or exists (
    select 1
    from public.message_threads
    where public.message_threads.id = thread_id
      and public.message_threads.fan_auth_user_id = auth.uid()
  )
);

drop policy if exists "Admins can update thread messages" on public.thread_messages;
create policy "Admins can update thread messages"
on public.thread_messages
for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Users can delete thread messages" on public.thread_messages;
create policy "Users can delete thread messages"
on public.thread_messages
for delete
using (
  public.is_admin()
  or exists (
    select 1
    from public.message_threads
    where public.message_threads.id = thread_id
      and public.message_threads.fan_auth_user_id = auth.uid()
  )
);

insert into storage.buckets (id, name, public)
values ('payment-proofs', 'payment-proofs', false)
on conflict (id) do update set public = excluded.public;

insert into storage.buckets (id, name, public)
values ('message-attachments', 'message-attachments', false)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Admins and owners can read payment proofs" on storage.objects;
create policy "Admins and owners can read payment proofs"
on storage.objects
for select
using (
  bucket_id = 'payment-proofs'
  and (
    public.is_admin()
    or auth.uid()::text = (storage.foldername(name))[1]
  )
);

drop policy if exists "Authenticated and guest uploads can write payment proofs" on storage.objects;
create policy "Authenticated and guest uploads can write payment proofs"
on storage.objects
for insert
with check (
  bucket_id = 'payment-proofs'
  and (
    public.is_admin()
    or auth.uid()::text = (storage.foldername(name))[1]
    or (
      auth.role() = 'anon'
      and (storage.foldername(name))[1] = 'guest'
    )
  )
);

drop policy if exists "Admins and owners can delete payment proofs" on storage.objects;
create policy "Admins and owners can delete payment proofs"
on storage.objects
for delete
using (
  bucket_id = 'payment-proofs'
  and (
    public.is_admin()
    or auth.uid()::text = (storage.foldername(name))[1]
  )
);

drop policy if exists "Thread participants can read message attachments" on storage.objects;
create policy "Thread participants can read message attachments"
on storage.objects
for select
using (
  bucket_id = 'message-attachments'
  and (
    public.is_admin()
    or exists (
      select 1
      from public.message_threads
      where public.message_threads.id::text = (storage.foldername(name))[1]
        and public.message_threads.fan_auth_user_id = auth.uid()
    )
  )
);

drop policy if exists "Thread participants can upload message attachments" on storage.objects;
create policy "Thread participants can upload message attachments"
on storage.objects
for insert
with check (
  bucket_id = 'message-attachments'
  and (
    public.is_admin()
    or exists (
      select 1
      from public.message_threads
      where public.message_threads.id::text = (storage.foldername(name))[1]
        and public.message_threads.fan_auth_user_id = auth.uid()
    )
  )
);

drop policy if exists "Thread participants can delete message attachments" on storage.objects;
create policy "Thread participants can delete message attachments"
on storage.objects
for delete
using (
  bucket_id = 'message-attachments'
  and (
    public.is_admin()
    or exists (
      select 1
      from public.message_threads
      where public.message_threads.id::text = (storage.foldername(name))[1]
        and public.message_threads.fan_auth_user_id = auth.uid()
    )
  )
);
