create table if not exists public.membership_requests (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  user_public_id bigint not null references public.user_profiles(public_id) on delete cascade,
  fan_name text not null default '',
  email text not null default '',
  plan text not null default 'INNER_CIRCLE',
  billing_cycle text not null default 'MONTHLY',
  talent_id bigint,
  talent_name text not null default 'All talents',
  amount_usd numeric(12, 2) not null default 0,
  currency_code text not null default 'USD',
  region text not null default '',
  payment_method text not null default 'BANK_TRANSFER',
  proof_summary text not null default '',
  proof_file_name text not null default '',
  status text not null default 'UNDER_REVIEW',
  risk text not null default 'low',
  activated_at timestamptz,
  reviewed_at timestamptz,
  submitted_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint membership_requests_plan_check
    check (plan in ('FREE', 'INNER_CIRCLE', 'CROWN_ACCESS')),
  constraint membership_requests_billing_cycle_check
    check (billing_cycle in ('MONTHLY', 'YEARLY')),
  constraint membership_requests_payment_method_check
    check (payment_method in ('BANK_TRANSFER', 'GIFT_CARD', 'CRYPTO')),
  constraint membership_requests_status_check
    check (status in ('UNDER_REVIEW', 'APPROVED', 'REJECTED', 'FLAGGED')),
  constraint membership_requests_risk_check
    check (risk in ('low', 'medium', 'high'))
);

create index if not exists membership_requests_auth_user_id_idx
  on public.membership_requests (auth_user_id);
create index if not exists membership_requests_user_public_id_idx
  on public.membership_requests (user_public_id);
create index if not exists membership_requests_status_idx
  on public.membership_requests (status);
create index if not exists membership_requests_submitted_at_idx
  on public.membership_requests (submitted_at desc);

drop trigger if exists set_membership_requests_updated_at on public.membership_requests;

create trigger set_membership_requests_updated_at
before update on public.membership_requests
for each row
execute function public.set_updated_at();

alter table public.membership_requests enable row level security;

drop policy if exists "Users can read own membership requests" on public.membership_requests;
create policy "Users can read own membership requests"
on public.membership_requests
for select
using (auth.uid() = auth_user_id or public.is_admin());

drop policy if exists "Users can insert own membership requests" on public.membership_requests;
create policy "Users can insert own membership requests"
on public.membership_requests
for insert
with check (auth.uid() = auth_user_id or public.is_admin());

drop policy if exists "Admins can update membership requests" on public.membership_requests;
create policy "Admins can update membership requests"
on public.membership_requests
for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete membership requests" on public.membership_requests;
create policy "Admins can delete membership requests"
on public.membership_requests
for delete
using (public.is_admin());

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  auth_user_id uuid references auth.users(id) on delete set null,
  user_public_id bigint references public.user_profiles(public_id) on delete set null,
  fan_name text not null default '',
  email text not null default '',
  order_type text not null default 'SERVICE',
  talent_id bigint,
  talent_name text not null default 'Selected talent',
  ref_code text not null,
  total_price numeric(12, 2) not null default 0,
  status text not null default 'UNDER_REVIEW',
  payment_method text,
  payment_proof text not null default '',
  payment_proof_file_name text not null default '',
  proof_summary text not null default '',
  requested_for text not null default '',
  region text not null default '',
  risk text not null default 'low',
  eta text not null default '',
  order_payload jsonb not null default '{}'::jsonb,
  reviewed_at timestamptz,
  submitted_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint orders_ref_code_unique unique (ref_code),
  constraint orders_order_type_check
    check (order_type in ('SERVICE', 'TICKET', 'SHOP')),
  constraint orders_status_check
    check (status in ('PENDING_PAYMENT', 'UNDER_REVIEW', 'FLAGGED', 'PAID', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED')),
  constraint orders_payment_method_check
    check (payment_method is null or payment_method in ('BANK_TRANSFER', 'GIFT_CARD', 'CRYPTO')),
  constraint orders_risk_check
    check (risk in ('low', 'medium', 'high'))
);

create index if not exists orders_auth_user_id_idx
  on public.orders (auth_user_id);
create index if not exists orders_user_public_id_idx
  on public.orders (user_public_id);
create index if not exists orders_status_idx
  on public.orders (status);
create index if not exists orders_submitted_at_idx
  on public.orders (submitted_at desc);
create index if not exists orders_ref_code_idx
  on public.orders (ref_code);

drop trigger if exists set_orders_updated_at on public.orders;

create trigger set_orders_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();

alter table public.orders enable row level security;

drop policy if exists "Users can read own orders" on public.orders;
create policy "Users can read own orders"
on public.orders
for select
using (auth.uid() = auth_user_id or public.is_admin());

drop policy if exists "Users can insert own orders" on public.orders;
create policy "Users can insert own orders"
on public.orders
for insert
with check (auth.uid() = auth_user_id or public.is_admin());

drop policy if exists "Admins can update orders" on public.orders;
create policy "Admins can update orders"
on public.orders
for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete orders" on public.orders;
create policy "Admins can delete orders"
on public.orders
for delete
using (public.is_admin());
